# stickers.py
STICKERS = {
    "welcome_general": "CAACAgQAAxkBAAMCaMQI4DqpxJjCicrNJTU3ZRhBDQMAAlcAAzb06QABOYOFe9k2ZKU2BA",
    "barca_celebration": "CAACAgIAAxkBAAMRaMQLxNe1QnaHseNck3KPFV66EyAAAuFpAAIupUhKiRYvDhNYPRY2BA",
    "after_name": "CAACAgQAAxkBAAMLaMQKbHA_ZS9mPWCX0Ksai1RVRXAAAk4TAAIhvbhQuv8wkfMmS9A2BA",
    "politics": "CAACAgIAAxkBAAMTaMQMASLnGZ-jizhIVWL5-MnO5ZEAAmgbAAL736hI4OXTyCM3j7c2BA",
    "partner_left": "CAACAgQAAxkBAAMSaMQL4BJToUApDANpbk6UX2yNNrUAAgQZAAJSLfFQwx5oMII7EJ82BA"
}
